---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: php-apache
 labels:
  app: php-apache
spec:
 replicas: 1
 selector:
  matchLabels:
   app: php-apache
 template:
  metadata: 
   labels:
    app: php-apache
  spec:
   containers:
   - name: php-apache
     image: chelkala/devops:tagversion
     ports:
     - containerPort: 80
     resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
     
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: php-apache
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: chelkala/devops:tagversion
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
     run: php-apache
spec:
    ports:
    - protocol: TCP
      port: 80
    selector:
      run: php-apache
